### ISSUE TITLE
cant find the workshop videos

### ISSUE THREAD

**Issue by iNoSec2** [wavestone-cdt/AD-security-workshop#4]
Hi, i saw you must have the entire workshop video recording on their youtube channel but cant find it. Do you have a copy of it?
Thanks for your time

**Comment by RemiEscourrou** [comment]
Hi,
The workshop was not recorded. We uploaded the technical demos associated to the workshop in the Videos folder.
Have a nice day

**Comment by iNoSec2** [comment]
Ok thank you and have a nice day too
